[package]
name = "flashlight"
version = "0.1.0"
authors = ["Tom Ward <tom@popdog.net>"]

[dependencies]
regex = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
lazy_static = "1.0"
docopt = "0.8"
indoc = "0.2"
isatty = "0.1"